from pathlib import Path
import subprocess, json, concurrent.futures
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'tests/revised';OUT.mkdir(parents=True,exist_ok=True)
book=json.loads((ROOT/'source/handbook.json').read_text(encoding='utf-8'))
cases={}
def case(i,s): cases[i]=s
case(0,'''DSU d(10); CHECK(d.merge(1,2)); CHECK(!d.merge(2,1)); CHECK(d.size(2)==2); CHECK(d.groups()==9);''')
case(1,'''UndoDSU d(10); int s=d.snapshot(); d.merge(1,2); d.merge(2,3); CHECK(d.size(3)==3); d.rollback(s); CHECK(!d.same(1,3)); CHECK(d.groups()==10);''')
case(2,'''WeightDSU<> d(20); for(int i=1;i<20;i++) CHECK(d.merge(i,i+1,3)); CHECK(d.diff(1,20)==57); CHECK(!d.merge(1,20,58)); CHECK(d.merge(20,1,-57));''')
case(3,'''NextDSU d(200000); for(int i=1;i<=200000;i++) d.erase(i); CHECK(d.next(1)==200001);''')
case(4,'''for(int n=1;n<=40;n++) {BIT<> b(n); vector<i64>a(n+1); for(int z=0;z<100;z++){int p=rnd(1,n),v=rnd(0,9);b.add(p,v);a[p]+=v;int l=rnd(1,n),r=rnd(l,n);CHECK(b.query(l,r)==accumulate(a.begin()+l,a.begin()+r+1,0LL));i64 sum=accumulate(a.begin(),a.end(),0LL),k=rnd(1,int(sum+1));int x=1; i64 s=0;while(x<=n && s+a[x]<k)s+=a[x++];CHECK(b.select(k)==x);}}''')
case(5,'''for(int n=1;n<=50;n++){vector<int>a(n+1);for(int&i:a)i=rnd(-20,20);auto f=[](int x,int y){return min(x,y);};ST<int,decltype(f)>s(a,f);for(int l=1;l<=n;l++)for(int r=l;r<=n;r++)CHECK(s.query(l,r)==*min_element(a.begin()+l,a.begin()+r+1));}''')
case(6,'''struct Info {i64 s=0;Info(i64 s=0):s(s){} Info operator+(Info b)const{return Info(s+b.s);}};
for(int n=1;n<=35;n++){vector<Info>a(n+1);vector<i64>b(n+1);for(int i=1;i<=n;i++)a[i]=b[i]=rnd(0,9);Seg<Info>s(a);for(int z=0;z<100;z++){int l=rnd(1,n),r=rnd(l,n);i64 sum=accumulate(b.begin()+l,b.begin()+r+1,0LL);CHECK(s.query(l,r).s==sum);i64 k=rnd(1,int(sum+1)),cur=0;int p=-1;for(int i=l;i<=r;i++){cur+=b[i];if(cur>=k){p=i;break;}}CHECK(s.first(l,r,[&](Info x){return x.s>=k;})==p);int x=rnd(1,n);b[x]=rnd(0,9);s.modify(x,Info(b[x]));}}
struct Str {string s;Str(string x=""):s(x){} Str operator+(Str b)const{return Str(s+b.s);}};vector<Str>a(8);for(int i=1;i<8;i++)a[i]=Str(string(1,'a'+i));Seg<Str>s(a);CHECK(s.query(2,6).s=="cdefg");''')
case(7,'''struct Tag {i64 mul=1,add=0;void apply(Tag b){mul*=b.mul;add=add*b.mul+b.add;}};struct Info {i64 sum=0;int len=0;Info(i64 s=0,int n=0):sum(s),len(n){}void apply(Tag b){sum=sum*b.mul+b.add*len;}Info operator+(Info b)const{return Info(sum+b.sum,len+b.len);}};
for(int n=1;n<=25;n++){vector<Info>a(n+1);vector<i64>b(n+1);for(int i=1;i<=n;i++)a[i]=Info(b[i]=rnd(0,9),1);LazySeg<Info,Tag>s(a);for(int z=0;z<50;z++){int l=rnd(1,n),r=rnd(l,n);Tag t;t.mul=rnd(0,1);t.add=rnd(0,5);s.apply(l,r,t);for(int i=l;i<=r;i++)b[i]=b[i]*t.mul+t.add;CHECK(s.query(l,r).sum==accumulate(b.begin()+l,b.begin()+r+1,0LL));}}''')
case(8,'''struct Info {int s=0;Info(int s=0):s(s){}void apply(Info b){s+=b.s;}Info operator+(Info b)const{return Info(s+b.s);}Info operator-(Info b)const{return Info(s-b.s);}};
PST<Info>s(20);vector<int>rt(1,0),a;for(int z=0;z<200;z++){int x=rnd(1,20);a.push_back(x);rt.push_back(s.modify(rt.back(),x,Info(1)));int l=rnd(0,z),r=rnd(l,z+1),v=rnd(1,20);int cnt=0;for(int i=l;i<r;i++)cnt+=a[i]<=v;CHECK(s.query(rt[l],rt[r],1,v).s==cnt);vector<int>b(a.begin()+l,a.begin()+r);sort(b.begin(),b.end());for(int k=1;k<=int(b.size());k++)CHECK(s.first(rt[l],rt[r],1,20,[&](Info t){return t.s>=k;})==b[k-1]);}''')
case(9,'''struct Info {i64 s=0;Info(i64 s=0):s(s){}Info operator+(Info b)const{return Info(s+b.s);}};DynSeg<Info>s(-50,50);int rt=0;map<int,i64>a;for(int z=0;z<500;z++){int x=rnd(-50,50);a[x]=rnd(-30,30);s.modify(rt,x,Info(a[x]));int l=rnd(-50,50),r=rnd(l,50);i64 sum=0;for(auto [p,v]:a)if(l<=p&&p<=r)sum+=v;CHECK(s.query(rt,l,r).s==sum);}''')
case(10,'''for(int n=1;n<=30;n++){vector<i64>a(n+1);for(int i=1;i<=n;i++)a[i]=rnd(-50,50);Beats s(a);for(int z=0;z<300;z++){int l=rnd(1,n),r=rnd(l,n),x=rnd(-100,100);s.chmin(l,r,x);for(int i=l;i<=r;i++)a[i]=min(a[i],i64(x));CHECK(s.sum(l,r)==accumulate(a.begin()+l,a.begin()+r+1,0LL));CHECK(s.maxi(l,r)==*max_element(a.begin()+l,a.begin()+r+1));}}Beats s(vector<i64>{0,0});s.chmin(1,1,LLONG_MIN);CHECK(s.maxi(1,1)==LLONG_MIN);''')
case(11,'''FHQ s;multiset<int>a;for(int z=0;z<2000;z++){int x=rnd(-20,20);if(rnd(0,1)){a.insert(x);s.insert(x);}else{auto it=a.find(x);bool ok=it!=a.end();CHECK(s.erase(x)==ok);if(ok)a.erase(it);}CHECK(s.size()==int(a.size()));CHECK(s.rank(x)==int(distance(a.begin(),a.lower_bound(x)))+1);int v;auto it=a.lower_bound(x);CHECK(s.prev(x,v)==(it!=a.begin()));if(it!=a.begin())CHECK(v==*prev(it));it=a.upper_bound(x);CHECK(s.next(x,v)==(it!=a.end()));if(it!=a.end())CHECK(v==*it);int k=0;for(int v:a)CHECK(s.kth(++k)==v);}''')
case(12,'''struct Policy {using Val=i64;using Info=i64;using Tag=i64;static Info identity(){return 0;}static Tag tagIdentity(){return 0;}static bool tagEmpty(Tag t){return t==0;}static Info make(Val v){return v;}static Info merge(Info a,Info b){return a+b;}static void apply(Val&v,Info&i,int n,Tag t){v+=t;i+=n*t;}static void compose(Tag&a,Tag b){a+=b;}static void reverseInfo(Info&){} };
Treap<Policy>s;vector<i64>a(20);iota(a.begin(),a.end(),0);int rt=s.build(a);for(int z=0;z<200;z++){int l=rnd(1,a.size()),r=rnd(l,a.size());if(rnd(0,1)){s.rangeReverse(rt,l,r);reverse(a.begin()+l-1,a.begin()+r);}else{int d=rnd(-5,5);s.apply(rt,l,r,d);for(int i=l-1;i<r;i++)a[i]+=d;}CHECK(s.query(rt,l,r)==accumulate(a.begin()+l-1,a.begin()+r,0LL));for(int i=0;i<int(a.size());i++)CHECK(s.tr[s.kth(rt,i+1)].val==a[i]);}int mid=s.erase(rt,3,5);a.erase(a.begin()+2,a.begin()+5);s.insert(rt,0,mid);CHECK(s.size(rt)==20);''')
case(13,'''OrderedSet<int>s;multiset<int>a;for(int z=0;z<500;z++){int x=rnd(-10,10);if(rnd(0,1)){s.insert(x);a.insert(x);}else{auto it=a.find(x);CHECK(s.erase(x)==(it!=a.end()));if(it!=a.end())a.erase(it);}CHECK(s.count(x)==int(a.count(x)));CHECK(s.orderOfKey(x)==int(distance(a.begin(),a.lower_bound(x))));int k=0,v;for(int y:a){CHECK(s.kth(++k,v));CHECK(v==y);}CHECK(!s.kth(0,v));}''')
case(14,'''LiChao s(-100,100);vector<pair<i64,i64>>a;for(int z=0;z<300;z++){i64 k=rnd(-100,100),b=rnd(-100,100);s.addLine(k,b);a.push_back({k,b});for(int x=-100;x<=100;x++){__int128 best=LiChao::inf;for(auto [k,b]:a)best=min(best,__int128(k)*x+b);CHECK(s.query(x)==best);}}''')
case(15,'''CHT s;vector<CHT::Point>a;for(int x=-20;x<=20;x++){CHT::Point p{x,rnd(-100,100)};s.addPoint(p);a.push_back(p);for(int z=0;z<10;z++){CHT::Point q{rnd(-20,20),rnd(1,10)};__int128 b=(__int128(1)<<120);for(auto p:a)b=min(b,CHT::dot(p,q));CHECK(s.query(q)==b);}}''')
case(16,'''for(int n=0;n<=100;n++){vector<int>a(n+1);for(int&i:a)i=rnd(-5,5);Cartesian<int>s(a);vector<int>v;function<void(int)>dfs=[&](int u){if(!u)return;if(s.left[u])CHECK(a[u]<=a[s.left[u]]);if(s.right[u])CHECK(a[u]<=a[s.right[u]]);dfs(s.left[u]);v.push_back(u);dfs(s.right[u]);};dfs(s.root);CHECK(v.size()==size_t(n));for(int i=1;i<=n;i++)CHECK(v[i-1]==i);}''')
case(17,'''int n=12;LCT s(n);vector<set<int>>g(n+1);vector<i64>a(n+1);auto path=[&](int u,int v){vector<int>p(n+1,-1);queue<int>q;q.push(u);p[u]=0;while(!q.empty()){int x=q.front();q.pop();for(int y:g[x])if(p[y]<0)p[y]=x,q.push(y);}vector<int>b;if(p[v]<0)return b;for(int x=v;x;x=p[x])b.push_back(x);return b;};for(int z=0;z<1500;z++){int u=rnd(1,n),v=rnd(1,n),op=rnd(0,3);auto b=path(u,v);if(op==0){bool ok=u!=v&&b.empty();CHECK(s.link(u,v)==ok);if(ok)g[u].insert(v),g[v].insert(u);}if(op==1){bool ok=g[u].count(v);CHECK(s.cut(u,v)==ok);if(ok)g[u].erase(v),g[v].erase(u);}if(op==2)a[u]=rnd(0,1023),s.setValue(u,a[u]);CHECK(s.connected(u,v)==!b.empty() || op==0 || op==1);b=path(u,v);if(!b.empty()){i64 val=0;for(int x:b)val^=a[x];CHECK(s.pathXor(u,v)==val);}}''')
case(18,'''TopK<3>s;map<int,i64>a;for(int z=0;z<200;z++){int k=rnd(0,8),v=rnd(-50,50);if(!a.count(k))a[k]=v;else a[k]=max(a[k],i64(v));s.add(k,v);int b=rnd(-1,8),c=rnd(-1,8);i64 ans=-TopK<3>::INF;for(auto [k,v]:a)if(k!=b&&k!=c)ans=max(ans,v);CHECK(s.get(b,c)==ans);}''')
case(19,'''for(int z=0;z<100;z++){int n=8;Dijkstra s(n);vector<vector<i64>>d(n+1,vector<i64>(n+1,s.inf));for(int i=1;i<=n;i++)d[i][i]=0;for(int k=0;k<25;k++){int u=rnd(1,n),v=rnd(1,n),w=rnd(0,10);s.addEdge(u,v,w);d[u][v]=min(d[u][v],i64(w));}for(int k=1;k<=n;k++)for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)if(d[i][k]!=s.inf&&d[k][j]!=s.inf)d[i][j]=min(d[i][j],d[i][k]+d[k][j]);for(int i=1;i<=n;i++){auto a=s.run(i);CHECK(a==d[i]);}}''')
case(20,'''for(int z=0;z<100;z++){int n=8;BFS01 s(n);vector<vector<int>>d(n+1,vector<int>(n+1,s.inf));for(int i=1;i<=n;i++)d[i][i]=0;for(int k=0;k<25;k++){int u=rnd(1,n),v=rnd(1,n),w=rnd(0,1);s.addEdge(u,v,w);d[u][v]=min(d[u][v],w);}for(int k=1;k<=n;k++)for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)if(d[i][k]!=s.inf&&d[k][j]!=s.inf)d[i][j]=min(d[i][j],d[i][k]+d[k][j]);for(int i=1;i<=n;i++)CHECK(s.run(i)==d[i]);}''')
case(21,'''i64 inf=1e15;vector<vector<i64>>d(4,vector<i64>(4,inf));for(int i=1;i<=3;i++)d[i][i]=0;d[1][2]=-3;d[2][3]=5;floyd(d,inf);CHECK(d[1][3]==2);CHECK(d[3][1]==inf);''')
case(22,'''vector<vector<int>>g(5);g[1]={2,3};g[2]={4};auto p=toposort(g);CHECK(p.size()==4);vector<int>pos(5);for(int i=0;i<4;i++)pos[p[i]]=i;for(int u=1;u<=4;u++)for(int v:g[u])CHECK(pos[u]<pos[v]);g[4]={1};CHECK(toposort(g).empty());''')
case(23,'''vector<Kruskal::Edge>e={{1,2,4},{2,3,-1},{1,3,2},{3,3,-99}};auto a=Kruskal::run(4,e);CHECK(a.first==1);CHECK(a.second.size()==2);''')
case(24,'''for(int z=0;z<300;z++){int n=3,m=3;vector<int>a(n+1),b(m+1);for(int i=1;i<=n;i++)for(int j=1;j<=m;j++){int x=rnd(0,1);a[i]+=x;b[j]+=x;}vector<vector<int>>c;CHECK(BiDegree::run(n,m,a,b,c));for(int i=1;i<=n;i++)CHECK(accumulate(c[i].begin(),c[i].end(),0)==a[i]);for(int j=1;j<=m;j++){int s=0;for(int i=1;i<=n;i++)s+=c[i][j];CHECK(s==b[j]);}}vector<vector<int>>c;CHECK(!BiDegree::run(2,2,{0,2,2},{0,1,1},c));''')
case(25,'''for(int z=0;z<30;z++){int n=6;APSP s(n);vector<vector<i64>>d(n+1,vector<i64>(n+1,s.INF));for(int i=1;i<=n;i++)d[i][i]=0;for(int k=0;k<30;k++){int u=rnd(1,n),v=rnd(1,n),w=rnd(0,10);s.addDirected(u,v,w);d[u][v]=min(d[u][v],i64(w));for(int t=1;t<=n;t++)for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)if(d[i][t]!=s.INF&&d[t][j]!=s.INF)d[i][j]=min(d[i][j],d[i][t]+d[t][j]);CHECK(s.dis==d);}}''')
case(26,'''for(int z=0;z<100;z++){int n=8;vector<vector<int>>g(n+1),r(n+1,vector<int>(n+1));for(int i=1;i<=n;i++)r[i][i]=1;for(int k=0;k<20;k++){int u=rnd(1,n),v=rnd(1,n);g[u].push_back(v);r[u][v]=1;}for(int k=1;k<=n;k++)for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)r[i][j]|=r[i][k]&r[k][j];SCC s(g);for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)CHECK((s.id[i]==s.id[j])==bool(r[i][j]&&r[j][i]));}''')
case(27,'''for(int z=0;z<300;z++){int n=5;TwoSAT s(n);vector<array<int,4>>a;for(int k=0;k<10;k++){array<int,4>v={rnd(1,n),rnd(0,1),rnd(1,n),rnd(0,1)};a.push_back(v);s.addClause(v[0],v[1],v[2],v[3]);}bool ok=false;for(int mask=0;mask<(1<<n);mask++){bool good=true;for(auto v:a)good&=(((mask>>(v[0]-1)&1)==v[1])||((mask>>(v[2]-1)&1)==v[3]));ok|=good;}CHECK(s.solve()==ok);if(ok)for(auto v:a)CHECK(s.answer[v[0]]==v[1]||s.answer[v[2]]==v[3]);s.setValue(1,true);s.setValue(1,false);CHECK(!s.solve());}''')
case(28,'''for(int z=0;z<200;z++){int n=7;Lowlink s(n);vector<pair<int,int>>e;for(int k=0;k<12;k++){int u=rnd(1,n),v=rnd(1,n);e.push_back({u,v});s.addEdge(u,v);}auto count=[&](int ban,int ed){vector<int>vis(n+1);int c=0;function<void(int)>dfs=[&](int u){vis[u]=1;for(int k=0;k<int(e.size());k++)if(k!=ed){auto [a,b]=e[k];if(a==u&&b!=ban&&!vis[b])dfs(b);if(b==u&&a!=ban&&!vis[a])dfs(a);}};for(int u=1;u<=n;u++)if(u!=ban&&!vis[u])c++,dfs(u);return c;};s.work();int base=count(0,-1);for(int i=0;i<int(e.size());i++)CHECK(s.bridge[i+1]==(count(0,i)>base));for(int u=1;u<=n;u++)CHECK(s.cut[u]==(count(u,-1)>base));}''')
case(29,'''EdgeBCC s(4);s.addEdge(1,2);s.addEdge(2,3);s.addEdge(3,1);s.addEdge(3,4);s.work();CHECK(s.id[1]==s.id[3]);CHECK(s.id[3]!=s.id[4]);''')
case(30,'''VertexBCC s(6);s.addEdge(1,2);s.addEdge(2,3);s.addEdge(3,1);s.addEdge(3,4);s.addEdge(4,5);s.addEdge(5,3);s.work();CHECK(s.comp.size()==4);CHECK(s.cut[3]);CHECK(!s.cut[1]);int e=0;for(auto v:s.tree)e+=v.size();CHECK(e/2==int(s.tree.size())-3);''')
case(31,'''vector<int>a;CHECK(EulerTrail::solve(4,{{1,2},{2,3},{3,1}},true,a));CHECK(a.size()==4);CHECK(!EulerTrail::solve(4,{{1,2},{3,4}},false,a));CHECK(EulerTrail::solve(2,{{1,1},{1,2},{1,2}},false,a));CHECK(a.size()==4);CHECK(EulerTrail::solve(0,{},false,a));''')
case(32,'''for(int z=0;z<500;z++){int n=rnd(0,6),m=rnd(0,6);HK s(n,m);vector<vector<int>>g(n+1);for(int u=1;u<=n;u++)for(int v=1;v<=m;v++)if(rnd(0,2)==0)s.addEdge(u,v),g[u].push_back(v);function<int(int,int)>dfs=[&](int u,int mask){if(u>n)return 0;int ans=dfs(u+1,mask);for(int v:g[u])if(!(mask>>(v-1)&1))ans=max(ans,1+dfs(u+1,mask|(1<<(v-1))));return ans;};int ans=s.solve();CHECK(ans==dfs(1,0));CHECK(s.solve()==ans);auto [a,b]=s.minVertexCover();CHECK(a.size()+b.size()==size_t(ans));for(int u=1;u<=n;u++)for(int v:g[u])CHECK(find(a.begin(),a.end(),u)!=a.end()||find(b.begin(),b.end(),v)!=b.end());}''')
case(33,'''for(int z=0;z<200;z++){int n=rnd(1,4),m=rnd(n,5);vector<vector<i64>>w(n+1,vector<i64>(m+1));for(int i=1;i<=n;i++)for(int j=1;j<=m;j++)w[i][j]=rnd(-10,10);function<i64(int,int)>dfs=[&](int u,int mask){if(u>n)return 0LL;i64 ans=-100000;for(int v=1;v<=m;v++)if(!(mask>>(v-1)&1))ans=max(ans,w[u][v]+dfs(u+1,mask|(1<<(v-1))));return ans;};auto a=Hungarian::maximum(w);CHECK(a.first==dfs(1,0));}''')
case(34,'''for(int z=0;z<300;z++){int n=6;Dinic s(n);vector<array<int,3>>e;for(int k=0;k<15;k++){int u=rnd(0,n-1),v=rnd(0,n-1),c=rnd(0,5);s.addEdge(u,v,c);e.push_back({u,v,c});}i64 best=LLONG_MAX;for(int mask=0;mask<(1<<n);mask++)if((mask&1)&&!(mask>>(n-1)&1)){i64 c=0;for(auto a:e)if((mask>>a[0]&1)&&!(mask>>a[1]&1))c+=a[2];best=min(best,c);}CHECK(s.maxFlow(0,n-1)==best);auto cut=s.minCut(0);i64 val=0;for(auto a:e)if(cut[a[0]]&&!cut[a[1]])val+=a[2];CHECK(val==best);CHECK(s.maxFlow(0,n-1)==0);}''')
case(35,'''for(int z=0;z<150;z++){int n=4;MCF s(n);vector<array<int,4>>e;for(int k=0;k<6;k++){int u=rnd(0,n-2),v=rnd(u+1,n-1),c=rnd(0,2),w=rnd(-4,5);s.addEdge(u,v,c,w);e.push_back({u,v,c,w});}int lim=rnd(1,5),bf=-1; i64 bc=0;vector<int>b(n);function<void(int,i64)>dfs=[&](int k,i64 cost){if(k==int(e.size())){for(int i=1;i<n-1;i++)if(b[i])return;int f=-b[0];if(f<0||f>lim||b[n-1]!=f)return;if(f>bf || (f==bf&&cost<bc))bf=f,bc=cost;return;}auto a=e[k];for(int f=0;f<=a[2];f++){b[a[0]]-=f;b[a[1]]+=f;dfs(k+1,cost+f*a[3]);b[a[0]]+=f;b[a[1]]-=f;}};dfs(0,0);auto a=s.flow(0,n-1,lim);CHECK(a.first==bf&&a.second==bc);}''')
case(36,'''for(int z=0;z<200;z++){int n=3;BoundFlow s(n);vector<array<int,4>>e;for(int k=0;k<5;k++){int u=rnd(0,n-1),v=rnd(0,n-1),l=rnd(0,1),r=rnd(l,2);s.addEdge(u,v,l,r);e.push_back({u,v,l,r});}bool circ=false;int best=-1;vector<int>b(n);function<void(int)>dfs=[&](int k){if(k==int(e.size())){if(b[0]==0&&b[1]==0&&b[2]==0)circ=true;if(!b[1]&&b[2]==-b[0]&&b[2]>=0)best=max(best,b[2]);return;}auto a=e[k];for(int f=a[2];f<=a[3];f++){b[a[0]]-=f;b[a[1]]+=f;dfs(k+1);b[a[0]]+=f;b[a[1]]-=f;}};dfs(0);vector<i64>a;CHECK(s.circulation(a)==circ);BoundFlow::Result r;CHECK(s.maxFlow(0,2,r)==(best>=0));if(best>=0)CHECK(r.value==best);}''')
case(37,'''for(int z=0;z<500;z++){Diff s(6);for(int k=0;k<16;k++)s.le(rnd(1,6),rnd(1,6),rnd(-3,5));vector<__int128>a,b;bool x=s.solve(a),y=s.solve(b,false);CHECK(x==y);if(x)for(auto e:s.edges)CHECK(a[e.v]-a[e.u]<=e.w);}''')
case(38,'''for(int z=0;z<200;z++){int n=12;vector<int>a(n+1);for(int i=1;i<=n;i++)a[i]=rnd(1,n);FuncGraph s(a);for(int u=1;u<=n;u++){int x=u;for(int k=0;k<100;k++){CHECK(s.jump(u,k)==x);x=a[x];}for(int v=1;v<=n;v++){int ans=-1,x=u;for(int k=0;k<=n;k++,x=a[x])if(x==v){ans=k;break;}CHECK(s.dis(u,v)==ans);}}}FuncGraph s({0,2,1});CHECK(s.jump(1,UINT64_MAX)==2);''')
case(39,'''for(int z=0;z<100;z++){int n=7;RangeGraph s(n);vector<vector<i64>>d(n+1,vector<i64>(n+1,s.INF));for(int i=1;i<=n;i++)d[i][i]=0;for(int k=0;k<20;k++){int l=rnd(1,n),r=rnd(l,n),x=rnd(1,n),y=rnd(x,n),w=rnd(0,10);s.rangeRange(l,r,x,y,w);for(int i=l;i<=r;i++)for(int j=x;j<=y;j++)d[i][j]=min(d[i][j],i64(w));}for(int k=1;k<=n;k++)for(int i=1;i<=n;i++)for(int j=1;j<=n;j++)if(d[i][k]!=s.INF&&d[k][j]!=s.INF)d[i][j]=min(d[i][j],d[i][k]+d[k][j]);for(int i=1;i<=n;i++)CHECK(s.distances(i)==d[i]);}''')
case(41,'''for(int z=0;z<200;z++){int n=4,m=7;vector<SecondMST::Edge>e;for(int k=0;k<m;k++)e.push_back({rnd(1,n),rnd(1,n),rnd(-5,5)});set<i64>vals;for(int mask=0;mask<(1<<m);mask++)if(__builtin_popcount(unsigned(mask))==n-1){vector<int>p(n+1);iota(p.begin(),p.end(),0);function<int(int)>f=[&](int x){return x==p[x]?x:p[x]=f(p[x]);};bool ok=true;i64 w=0;for(int k=0;k<m;k++)if(mask>>k&1){int u=f(e[k].u),v=f(e[k].v);if(u==v)ok=false;p[u]=v;w+=e[k].w;}if(ok)vals.insert(w);}i64 a,b;CHECK(SecondMST::solve(n,e,a,b)==!vals.empty());if(!vals.empty()){CHECK(a==*vals.begin());CHECK(b==(vals.size()>1?*next(vals.begin()):SecondMST::INF));}}''')
case(43,'''for(int z=0;z<200;z++){int n=rnd(0,30);vector<uint32_t>a(n);for(auto&x:a)x=rnd(0,511);if(n&&z%2==0)a[0]|=1u<<31;auto ans=XorMST::run(a);vector<uint64_t>d(n,UINT64_MAX);vector<bool>v(n);uint64_t sum=0;if(n)d[0]=0;for(int k=0;k<n;k++){int u=-1;for(int i=0;i<n;i++)if(!v[i]&&(u<0||d[i]<d[u]))u=i;v[u]=1;sum+=d[u];for(int i=0;i<n;i++)d[i]=min(d[i],uint64_t(a[i]^a[u]));}CHECK(ans.first==int64_t(sum));CHECK(ans.second.size()==size_t(max(0,n-1)));}''')
case(44,'''for(int z=0;z<100;z++){int n=7;vector<i64>w(n+1);vector<pair<int,int>>e;for(int i=1;i<=n;i++)w[i]=rnd(-10,10);for(int k=0;k<12;k++)e.push_back({rnd(1,n),rnd(1,n)});i64 best=0;for(int m=0;m<(1<<n);m++){bool ok=true;for(auto [u,v]:e)if((m>>(u-1)&1)&&!(m>>(v-1)&1))ok=false;i64 s=0;for(int i=1;i<=n;i++)if(m>>(i-1)&1)s+=w[i];if(ok)best=max(best,s);}auto a=maxClosure(w,e);CHECK(a.first==best);}''')
case(45,'''for(int z=0;z<200;z++){int n=8;vector<Boruvka::Edge>e;for(int k=0;k<20;k++)e.push_back({rnd(1,n),rnd(1,n),rnd(-20,20)});auto a=Boruvka::run(n,e);sort(e.begin(),e.end(),[](auto x,auto y){return x.w<y.w;});vector<int>p(n+1);iota(p.begin(),p.end(),0);function<int(int)>f=[&](int x){return x==p[x]?x:p[x]=f(p[x]);};i64 w=0;int cnt=n;for(auto v:e){int x=f(v.u),y=f(v.v);if(x!=y)p[x]=y,w+=v.w,--cnt;}CHECK(a.weight==w&&a.comp==cnt);}''')

# Additional test cases are loaded from a separately editable companion.
exec((ROOT/'rebuild/verify_more.py').read_text(encoding='utf-8'))

prefix='''#include <bits/stdc++.h>\n#include <ext/pb_ds/assoc_container.hpp>\n#include <ext/pb_ds/tree_policy.hpp>\nusing namespace std;\nusing i64=long long;\nmt19937 rng(712367);\nint rnd(int l,int r){return uniform_int_distribution<int>(l,r)(rng);}\nlong long checks=0;\n#define CHECK(x) do {++checks;if(!(x)){cerr<<"FAIL "<<__FILE__<<":"<<__LINE__<<" "<<#x<<"\\n";abort();}} while(0)\n'''
targets=[x for x in book if x['code']]
missing=[x['id'] for x in targets if x['id'] not in cases]
assert not missing,missing
groups=[targets[i:i+18] for i in range(0,len(targets),18)]
def run(k,g):
    c=prefix
    for x in g:
        c+='\nnamespace T'+str(x['id'])+' {\n#include "'+(ROOT/'code'/x['code']).as_posix()+'"\nvoid test(){\n'+cases[x['id']]+'\n}\n}\n'
    c+='int main(){\n'
    for x in g:c+='T'+str(x['id'])+'::test(); cout<<"PASS '+x['key']+' "<<checks<<"\\n";\n'
    c+='}\n'
    p=OUT/f'suite_{k}.cpp';p.write_text(c,encoding='utf-8');exe=OUT/f'suite_{k}.exe'
    r=subprocess.run(['D:/msys2/mingw64/bin/g++.exe','-std=gnu++17','-O2',str(p),'-o',str(exe)],capture_output=True,text=True,encoding='utf-8',errors='replace')
    if r.returncode:return dict(group=k,ok=False,phase='compile',log=r.stderr)
    try:r=subprocess.run([str(exe)],capture_output=True,text=True,encoding='utf-8',errors='replace',timeout=180)
    except subprocess.TimeoutExpired:return dict(group=k,ok=False,phase='timeout',log='runtime >180s')
    return dict(group=k,ok=r.returncode==0,phase='run',log=r.stdout+r.stderr)
import sys
selected=[(k,g) for k,g in enumerate(groups) if len(sys.argv)==1 or str(k) in sys.argv[1:]]
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as ex:rs=list(ex.map(lambda z:run(*z),selected))
if len(sys.argv)>1 and (OUT/'verification.json').exists():
    previous=json.loads((OUT/'verification.json').read_text(encoding='utf-8'))
    merged={x['group']:x for x in previous};merged.update({x['group']:x for x in rs});saved=list(merged.values())
else:saved=rs
(OUT/'verification.json').write_text(json.dumps(saved,ensure_ascii=False,indent=2),encoding='utf-8')
for r in rs:print(r['group'],r['ok'],r['phase'],r['log'][-7000:])
print('PASSED GROUPS',sum(r['ok'] for r in rs),'/',len(rs))
